language: node_js

node_js:
  - '6.6.0'

install:
  - '( cd backend && npm install )'
  - '( cd frontend && npm install )'

script:
  - '( cd backend && npm run test )'
  - '( cd frontend && npm run test )'

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules
