language: node_js

node_js:
  - '6.6.0'

install:
  - '( cd backend && npm install )'

script:
  - '( cd backend && npm run dist )'

cache:
  directories:
    - backend/node_modules

notifications:
  webhooks:
    # trigger Buildtime Trend Service to parse Travis CI log
    - https://buildtimetrend.herokuapp.com/travis
